### ISSUE TITLE
Change README Travis Badge link

### ISSUE THREAD

**Issue by yukiisbored** [coala/coala-eclipse#33] opened 2017-04-24 13:23 UTC
The travis badge link is still using `coala-analyzer` instead of `coala`.

**Comment by aashutoshrathi** [comment] 2017-11-05 20:13
This can be a `initiatives/gci` issue.

**Comment by yukiisbored** [comment] 2017-11-08 08:24
@aashutoshrathi This is meant not just as a GCI issue but as a general newcomer issue.

**Comment by yukiisbored** [comment] 2017-11-08 08:25
not sure if adding initiatives/gci is important.

**Comment by xyzyg** [comment] 2017-11-23 13:32
hi i am a beginner and i would like to work on this issue can someone give me any pointers ?

**Comment by nalinbhardwaj** [comment] 2018-10-08 10:51
This should be closed, it was fixed in https://github.com/coala/coala-eclipse/commit/fd3b7f037ef616cb8b22c7312912ed51000567fb

**Comment by jayvdb** [comment] 2018-10-08 13:35
Duplicate of https://github.com/coala/coala-eclipse/issues/26

**Closed** 2018-10-08 13:35 UTC
Labels: difficulty/newcomer
